from __future__ import annotations

import csv
import html
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "store_metadata" / "google_play_titles.tsv"
ANDROID_RES = ROOT / "android" / "app" / "src" / "main" / "res"
IOS_RUNNER = ROOT / "ios" / "Runner"
IOS_PROJECT = ROOT / "ios" / "Runner.xcodeproj" / "project.pbxproj"
DART_OUTPUT = ROOT / "lib" / "l10n" / "app_titles.dart"

# Stable Xcode identifiers reserved for the localized InfoPlist.strings group.
VARIANT_GROUP_ID = "A11A00000000000000000001"
BUILD_FILE_ID = "A11A00000000000000000002"
FILE_ID_PREFIX = "A11A0000000000000001"


def load_titles() -> list[dict[str, str]]:
    with CATALOG.open(encoding="utf-8", newline="") as source:
        return list(csv.DictReader(source, delimiter="\t"))


def dart_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def generate_dart(rows: list[dict[str, str]]) -> None:
    lines = [
        "// Generated by scripts/generate_localized_app_names.py.",
        "// Keep store_metadata/google_play_titles.tsv as the source of truth.",
        "abstract final class AppTitles {",
        "  static const byLanguage = <String, String>{",
    ]
    for row in rows:
        lines.append(
            f"    '{dart_quote(row['app_locale'])}': "
            f"'{dart_quote(row['title'])}',"
        )
    lines.extend(
        [
            "  };",
            "",
            "  static String forLanguage(String languageCode) =>",
            "      byLanguage[languageCode] ?? byLanguage['en']!;",
            "}",
            "",
        ]
    )
    DART_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


def generate_android(rows: list[dict[str, str]]) -> None:
    for row in rows:
        language = row["app_locale"]
        directory = ANDROID_RES / ("values" if language == "en" else f"values-{language}")
        directory.mkdir(parents=True, exist_ok=True)
        title = html.escape(row["title"], quote=False)
        (directory / "strings.xml").write_text(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            "<resources>\n"
            f'    <string name="app_name">{title}</string>\n'
            "</resources>\n",
            encoding="utf-8",
        )


def generate_ios(rows: list[dict[str, str]]) -> list[tuple[str, str]]:
    references: list[tuple[str, str]] = []
    for index, row in enumerate(rows, start=1):
        language = row["app_locale"]
        title = row["title"].replace("\\", "\\\\").replace('"', '\\"')
        directory = IOS_RUNNER / f"{language}.lproj"
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "InfoPlist.strings").write_text(
            f'"CFBundleDisplayName" = "{title}";\n'
            f'"CFBundleName" = "{title}";\n',
            encoding="utf-8",
        )
        references.append((f"{FILE_ID_PREFIX}{index:04X}", language))
    return references


def patch_xcode_project(references: list[tuple[str, str]]) -> None:
    project = IOS_PROJECT.read_text(encoding="utf-8")
    languages = [language for _, language in references]
    known_regions = "\n".join(
        f"\t\t\t\t{language}," for language in languages
    )
    project = project.replace(
        "\t\t\tknownRegions = (\n\t\t\t\ten,\n\t\t\t\tBase,\n\t\t\t);",
        "\t\t\tknownRegions = (\n"
        f"{known_regions}\n"
        "\t\t\t\tBase,\n"
        "\t\t\t);",
        1,
    )
    if VARIANT_GROUP_ID in project:
        IOS_PROJECT.write_text(project, encoding="utf-8")
        return

    file_refs = "\n".join(
        f'\t\t{file_id} /* {language} */ = {{isa = PBXFileReference; '
        f'lastKnownFileType = text.plist.strings; name = {language}; '
        f'path = {language}.lproj/InfoPlist.strings; sourceTree = "<group>"; }};'
        for file_id, language in references
    )
    project = project.replace(
        "/* Begin PBXBuildFile section */\n",
        "/* Begin PBXBuildFile section */\n"
        f"\t\t{BUILD_FILE_ID} /* InfoPlist.strings in Resources */ = "
        f"{{isa = PBXBuildFile; fileRef = {VARIANT_GROUP_ID} /* InfoPlist.strings */; }};\n",
        1,
    )
    project = project.replace(
        "/* End PBXFileReference section */",
        f"{file_refs}\n/* End PBXFileReference section */",
        1,
    )
    project = project.replace(
        "\t\t\t\t97C147021CF9000F007C117D /* Info.plist */,\n",
        "\t\t\t\t97C147021CF9000F007C117D /* Info.plist */,\n"
        f"\t\t\t\t{VARIANT_GROUP_ID} /* InfoPlist.strings */,\n",
        1,
    )
    children = "\n".join(
        f"\t\t\t\t{file_id} /* {language} */," for file_id, language in references
    )
    variant_section = (
        "/* Begin PBXVariantGroup section */\n"
        f"\t\t{VARIANT_GROUP_ID} /* InfoPlist.strings */ = {{\n"
        "\t\t\tisa = PBXVariantGroup;\n"
        "\t\t\tchildren = (\n"
        f"{children}\n"
        "\t\t\t);\n"
        "\t\t\tname = InfoPlist.strings;\n"
        "\t\t\tsourceTree = \"<group>\";\n"
        "\t\t};\n"
        "/* End PBXVariantGroup section */\n\n"
    )
    project = project.replace(
        "/* Begin XCBuildConfiguration section */",
        variant_section + "/* Begin XCBuildConfiguration section */",
        1,
    )
    resources_anchor = "\t\t\tfiles = (\n\t\t\t\t97C147011CF9000F007C117D /* LaunchScreen.storyboard in Resources */,"
    project = project.replace(
        resources_anchor,
        "\t\t\tfiles = (\n"
        f"\t\t\t\t{BUILD_FILE_ID} /* InfoPlist.strings in Resources */,\n"
        "\t\t\t\t97C147011CF9000F007C117D /* LaunchScreen.storyboard in Resources */,",
        1,
    )
    IOS_PROJECT.write_text(project, encoding="utf-8")


def main() -> int:
    rows = load_titles()
    generate_dart(rows)
    generate_android(rows)
    references = generate_ios(rows)
    patch_xcode_project(references)
    print(f"Generated localized app names for {len(rows)} languages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
